### PR TITLE
Update project dependencies

### PR DESCRIPTION
**Pull request by friederbluemle**
Various project dependency updates. See individual commits for details.

<sub><sup>Please NO GitHub rebase/squash merges. If you'd like me to combine some or all of the commits, please let me know, and I will update my branch. Thank you.</sup></sub>

### CODE REVIEW

**Comment by vincentbrison** [comment]
Hello,

Thanks for your additions ! Have you any idea why Travis is not updating the config according to https://github.com/vincentbrison/vb-android-app-quality/pull/21/commits/c80f73c9b3d19704a35b8050190080cbe8994a73 ?

**Comment by vincentbrison** [comment]
Ok, it looks like your merge commit https://github.com/vincentbrison/vb-android-app-quality/commit/9ed3708e245f5f02e93ad90d47344e479bf9d742 is cancelling your changes from here https://github.com/vincentbrison/vb-android-app-quality/pull/21/commits/c80f73c9b3d19704a35b8050190080cbe8994a73. In order to re-enable the CI validation, we should keep your changes from https://github.com/vincentbrison/vb-android-app-quality/pull/21/commits/c80f73c9b3d19704a35b8050190080cbe8994a73. Can you make the change ? Thank you !

**Comment by friederbluemle** [comment]
@vincentbrison Very strange Travis CI error. Let me to a `--no-edit` fixup commit rewrite the hash and force push.

**Comment by friederbluemle** [comment]
Okay it works now.. Maybe somehow Travis incorrectly reported the status of the previous build to GitHub.

**Comment by vincentbrison** [comment]
Thanks.

**Pull request merged**
